export const mockColumns = [
  { id: 'col-1', boardId: '1', title: 'To Do' },
  { id: 'col-2', boardId: '1', title: 'In Progress' },
  { id: 'col-3', boardId: '1', title: 'Done' },
  { id: 'col-1', boardId: '2', title: 'To Do' },
  { id: 'col-2', boardId: '2', title: 'In Progress' },
  { id: 'col-3', boardId: '2', title: 'Done' },
  { id: 'col-3', boardId: '3', title: 'To Do' },
  { id: 'col-2', boardId: '3', title: 'In Progress' },
  { id: 'col-1', boardId: '3', title: 'Done' },
];

export const mockTasks = [
  {
    id: 'task-1',
    title: 'Fix login bug',
    description:
      'Користувачі не можуть увійти з мобільних пристроїв lorem ipsum dolor sit amet.',
    priority: 'High',
    deadline: '2025-10-10',
    columnId: 'col-1',
    boardId: '1',
  },
  {
    id: 'task-2',
    title: 'Update landing page',
    description: 'Додати секцію з відгуками клієнтів та покращити SEO.',
    priority: 'Medium',
    deadline: '2025-10-15',
    columnId: 'col-1',
    boardId: '1',
  },
  {
    id: 'task-3',
    title: 'Database backup',
    description: 'Налаштувати щоденний резервний бекап на хмару.',
    priority: 'Low',
    deadline: '2025-10-20',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-4',
    title: 'Refactor header component',
    description: 'Оптимізувати код, прибрати дублювання стилів.',
    priority: 'Without',
    deadline: '2025-10-05',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-5',
    title: 'Prepare presentation',
    description: 'Зробити слайди для демо-зустрічі з клієнтом.',
    priority: 'High',
    deadline: '2025-10-12',
    columnId: 'col-3',
    boardId: '1',
  },
  {
    id: 'task-6',
    title: 'Improve dark mode',
    description: 'Додати підтримку темної теми для дашборду.',
    priority: 'Medium',
    deadline: '2025-10-18',
    columnId: 'col-3',
    boardId: '1',
  },
  {
    id: 'task-7',
    title: 'Fix API error handling',
    description: 'Додати детальну обробку помилок у сервісі.',
    priority: 'High',
    deadline: '2025-11-02',
    columnId: 'col-1',
    boardId: '2',
  },
  {
    id: 'task-8',
    title: 'Redesign footer',
    description: 'Оновити стилі та додати соцмережі.',
    priority: 'Low',
    deadline: '2025-11-10',
    columnId: 'col-1',
    boardId: '2',
  },
  {
    id: 'task-9',
    title: 'Set up CI/CD',
    description: 'Налаштувати Github Actions для автоматичного деплою.',
    priority: 'High',
    deadline: '2025-11-15',
    columnId: 'col-2',
    boardId: '2',
  },
  {
    id: 'task-10',
    title: 'Code review session',
    description: 'Провести ревʼю основних модулів.',
    priority: 'Medium',
    deadline: '2025-11-20',
    columnId: 'col-2',
    boardId: '2',
  },
  {
    id: 'task-11',
    title: 'Add animations',
    description: 'Додати плавні анімації на кнопки.',
    priority: 'Low',
    deadline: '2025-11-25',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-12',
    title: 'Test mobile UI',
    description: 'Протестувати верстку на різних екранах.',
    priority: 'Without',
    deadline: '2025-11-28',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-13',
    title: 'Migrate database',
    description: 'Перенести дані з MongoDB до PostgreSQL.',
    priority: 'High',
    deadline: '2025-12-01',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-14',
    title: 'Fix console warnings',
    description: 'Прибрати всі попередження в консолі React.',
    priority: 'Low',
    deadline: '2025-12-03',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-15',
    title: 'Write documentation',
    description: 'Додати README та документацію для API.',
    priority: 'Medium',
    deadline: '2025-12-05',
    columnId: 'col-2',
    boardId: '3',
  },
  {
    id: 'task-16',
    title: 'Audit security',
    description: 'Перевірити автентифікацію та права доступу.',
    priority: 'High',
    deadline: '2025-12-07',
    columnId: 'col-2',
    boardId: '3',
  },
  {
    id: 'task-17',
    title: 'Add charts',
    description: 'Інтегрувати бібліотеку Recharts для графіків.',
    priority: 'Without',
    deadline: '2025-12-09',
    columnId: 'col-3',
    boardId: '3',
  },
  {
    id: 'task-18',
    title: 'Dark mode testing',
    description: 'Перевірити коректність кольорів у темній темі.',
    priority: 'Medium',
    deadline: '2025-12-11',
    columnId: 'col-3',
    boardId: '3',
  },
  {
    id: 'task-19',
    title: 'Generated Task 19',
    description: 'Тестовий опис для завдання 19.',
    priority: 'High',
    deadline: '2025-10-11',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-20',
    title: 'Generated Task 20',
    description: 'Тестовий опис для завдання 20.',
    priority: 'Low',
    deadline: '2025-11-12',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-21',
    title: 'Generated Task 21',
    description: 'Тестовий опис для завдання 21.',
    priority: 'Medium',
    deadline: '2025-12-13',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-22',
    title: 'Generated Task 22',
    description: 'Тестовий опис для завдання 22.',
    priority: 'Without',
    deadline: '2025-10-14',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-23',
    title: 'Generated Task 23',
    description: 'Тестовий опис для завдання 23.',
    priority: 'High',
    deadline: '2025-11-15',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-24',
    title: 'Generated Task 24',
    description: 'Тестовий опис для завдання 24.',
    priority: 'Low',
    deadline: '2025-12-16',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-25',
    title: 'Generated Task 25',
    description: 'Тестовий опис для завдання 25.',
    priority: 'Medium',
    deadline: '2025-10-17',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-26',
    title: 'Generated Task 26',
    description: 'Тестовий опис для завдання 26.',
    priority: 'High',
    deadline: '2025-11-18',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-27',
    title: 'Generated Task 27',
    description: 'Тестовий опис для завдання 27.',
    priority: 'Without',
    deadline: '2025-12-19',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-28',
    title: 'Generated Task 28',
    description: 'Тестовий опис для завдання 28.',
    priority: 'Medium',
    deadline: '2025-10-20',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-29',
    title: 'Generated Task 29',
    description: 'Тестовий опис для завдання 29.',
    priority: 'Low',
    deadline: '2025-11-21',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-30',
    title: 'Generated Task 30',
    description: 'Тестовий опис для завдання 30.',
    priority: 'High',
    deadline: '2025-12-22',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-31',
    title: 'Generated Task 31',
    description: 'Тестовий опис для завдання 31.',
    priority: 'Without',
    deadline: '2025-10-23',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-32',
    title: 'Generated Task 32',
    description: 'Тестовий опис для завдання 32.',
    priority: 'Medium',
    deadline: '2025-11-24',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-33',
    title: 'Generated Task 33',
    description: 'Тестовий опис для завдання 33.',
    priority: 'Low',
    deadline: '2025-12-25',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-34',
    title: 'Generated Task 34',
    description: 'Тестовий опис для завдання 34.',
    priority: 'High',
    deadline: '2025-10-26',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-35',
    title: 'Generated Task 35',
    description: 'Тестовий опис для завдання 35.',
    priority: 'Medium',
    deadline: '2025-11-27',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-36',
    title: 'Generated Task 36',
    description: 'Тестовий опис для завдання 36.',
    priority: 'Low',
    deadline: '2025-12-28',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-37',
    title: 'Generated Task 37',
    description: 'Тестовий опис для завдання 37.',
    priority: 'Without',
    deadline: '2025-10-29',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-38',
    title: 'Generated Task 38',
    description: 'Тестовий опис для завдання 38.',
    priority: 'High',
    deadline: '2025-11-30',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-39',
    title: 'Generated Task 39',
    description: 'Тестовий опис для завдання 39.',
    priority: 'Medium',
    deadline: '2025-12-10',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-40',
    title: 'Generated Task 40',
    description: 'Тестовий опис для завдання 40.',
    priority: 'Low',
    deadline: '2025-10-12',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-41',
    title: 'Generated Task 41',
    description: 'Тестовий опис для завдання 41.',
    priority: 'High',
    deadline: '2025-11-13',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-42',
    title: 'Generated Task 42',
    description: 'Тестовий опис для завдання 42.',
    priority: 'Without',
    deadline: '2025-12-14',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-43',
    title: 'Generated Task 43',
    description: 'Тестовий опис для завдання 43.',
    priority: 'Medium',
    deadline: '2025-10-15',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-44',
    title: 'Generated Task 44',
    description: 'Тестовий опис для завдання 44.',
    priority: 'Low',
    deadline: '2025-11-16',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-45',
    title: 'Generated Task 45',
    description: 'Тестовий опис для завдання 45.',
    priority: 'High',
    deadline: '2025-12-17',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-46',
    title: 'Generated Task 46',
    description: 'Тестовий опис для завдання 46.',
    priority: 'Medium',
    deadline: '2025-10-18',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-47',
    title: 'Generated Task 47',
    description: 'Тестовий опис для завдання 47.',
    priority: 'Without',
    deadline: '2025-11-19',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-48',
    title: 'Generated Task 48',
    description: 'Тестовий опис для завдання 48.',
    priority: 'Low',
    deadline: '2025-12-20',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-49',
    title: 'Generated Task 49',
    description: 'Тестовий опис для завдання 49.',
    priority: 'Medium',
    deadline: '2025-10-21',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-50',
    title: 'Generated Task 50',
    description: 'Тестовий опис для завдання 50.',
    priority: 'High',
    deadline: '2025-11-22',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-51',
    title: 'Generated Task 51',
    description: 'Тестовий опис для завдання 51.',
    priority: 'Low',
    deadline: '2025-12-23',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-52',
    title: 'Generated Task 52',
    description: 'Тестовий опис для завдання 52.',
    priority: 'Without',
    deadline: '2025-10-24',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-53',
    title: 'Generated Task 53',
    description: 'Тестовий опис для завдання 53.',
    priority: 'Medium',
    deadline: '2025-11-25',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-54',
    title: 'Generated Task 54',
    description: 'Тестовий опис для завдання 54.',
    priority: 'High',
    deadline: '2025-12-26',
    columnId: 'col-1',
    boardId: '3',
  },
  {
    id: 'task-55',
    title: 'Generated Task 55',
    description: 'Тестовий опис для завдання 55.',
    priority: 'Low',
    deadline: '2025-10-27',
    columnId: 'col-2',
    boardId: '1',
  },
  {
    id: 'task-56',
    title: 'Generated Task 56',
    description: 'Тестовий опис для завдання 56.',
    priority: 'Medium',
    deadline: '2025-11-28',
    columnId: 'col-3',
    boardId: '2',
  },
  {
    id: 'task-57',
    title: 'Generated Task 57',
    description: 'Тестовий опис для завдання 57.',
    priority: 'Without',
    deadline: '2025-12-29',
    columnId: 'col-1',
    boardId: '3',
  },
];
